prog: menu.o Enigme.o enigmetf.o temps.o minimap.o bg.o perso.o ennemi.o main.o
	gcc menu.o Enigme.o enigmetf.o temps.o minimap.o bg.o ennemi.o perso.o main.o -o prog -lSDL -lSDL_ttf -g -lSDL_image -lSDL_mixer
main.o:main.c
	gcc -c main.c -g
perso.o:perso.c
	gcc -c perso.c -g
ennemi.o:ennemi.c
	gcc -c ennemi.c -g
bg.o:bg.c
	gcc -c bg.c -g
minimap.o:minimap.c
	gcc -c minimap.c -g
pers.o:pers.c
	gcc -c pers.c -g
temps.o:temps.c 
	gcc -c temps.c -g
enigmetf.o:enigmetf.c
	gcc -c enigmetf.c
Enigme.o:Enigme.c
	gcc -c Enigme.c -g
menu.o:menu.c
	gcc -c menu.c -g
